# Telegram Channels Configuration
# List of public Telegram channels to monitor for violations reports

channels:

  - name: "Dama Post"
    url: "https://t.me/dama_post_syria"
    description: "Dama Post"
    active: true
    priority: "medium"
    language: "ar"
    assigned_regions:
      - "دمشق"
      - "ريف دمشق"
      - "درعا"
      - "ريف درعا"
      - "السويداء"
      - "القنيطرة"
    filtering:
      min_keyword_matches: 2
      require_context_keywords: true
      min_text_length: 30
      exclude_patterns: []
      enforce_region_filter: true

  - name: "Naher Media"
    url: "https://t.me/nahermedia"
    description: "Naher Media"
    active: true
    priority: "medium"
    language: "ar"
    assigned_regions:
      - "حلب"
      - "ريف حلب"
      - "إدلب"
      - "ريف إدلب"
      - "حمص"
      - "ريف حمص"
      - "حماة"
      - "ريف حماة"
    filtering:
      min_keyword_matches: 2
      require_context_keywords: true
      min_text_length: 30
      exclude_patterns: []
      enforce_region_filter: true

  - name: "Halab Today"
    url: "https://t.me/HalabTodayTV"
    description: "Halab Today"
    active: true
    priority: "low"
    language: "ar"
    assigned_regions:
      - "حلب"
      - "إدلب"
      - "ريف إدلب"
      - "ريف حلب"
    filtering:
      min_keyword_matches: 1
      require_context_keywords: true
      min_text_length: 40
      enforce_region_filter: true

  - name: "صوت العاصمة"
    url: "https://t.me/damascusv011"
    description: "صوت العاصمة"
    active: true
    priority: "high"
    language: "ar"
    assigned_regions:
      - "دمشق"
      - "ريف دمشق"
    filtering:
      min_keyword_matches: 1
      require_context_keywords: true
      enforce_region_filter: true

  - name: "سوريا لحظة بلحظة"
    url: "https://t.me/Almohrar"
    description: "سوريا لحظة بلحظة"
    active: true
    priority: "medium"
    language: "ar"
    assigned_regions:
      - "حلب"
      - "دمشق"
      - "حمص"
      - "درعا"
      - "ريف دمشق"
    filtering:
      min_keyword_matches: 1
      require_context_keywords: true
      enforce_region_filter: false
      
  - name: "alkhabour"
    url: "https://t.me/alkhabour"
    description: "alkhabour"
    active: true
    priority: "medium"
    language: "ar"
    assigned_regions:
      - "دير الزور"
      - "الرقة"
      - "ريف الرقة"
      - "الحسكة"
      - "ريف الحسكة"
    filtering:
      min_keyword_matches: 2
      require_context_keywords: true
      min_text_length: 50
      exclude_patterns: ["طقس", "أحوال جوية", "اقتصاد", "سياسة"]
      enforce_region_filter: true

  - name: "D24net"
    url: "https://t.me/D24net"
    description: "D24net"
    active: true
    priority: "medium"
    language: "ar"

  - name: "horanfree"
    url: "https://t.me/HoranFreeMedia"
    description: "horanfree"
    active: true
    priority: "medium"
    language: "ar"
    assigned_regions:
      - "درعا"
      - "ريف درعا"
      - "القنيطرة"
      - "السويداء"      
    filtering:
      min_keyword_matches: 2
      require_context_keywords: true
      min_text_length: 50
      exclude_patterns: ["طقس", "أحوال جوية", "اقتصاد", "سياسة"]
      enforce_region_filter: true

# Scraping configuration
scraping:
  # How often to run the scraper (in minutes)
  interval: 5
  
  # How far back to look for messages (in minutes)
  lookback_window: 60
  
  # Maximum number of messages to process per channel per run
  max_messages_per_channel: 50
  
  # Timeout for HTTP requests (in seconds)
  request_timeout: 30
  
  # Retry configuration
  max_retries: 3
  retry_delay: 5000  # milliseconds
  
  # User agent for web scraping
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Enhanced filtering configuration
filtering:
  # Global filtering settings
  global:
    min_keyword_matches: 3
    require_context_keywords: true
    min_text_length: 50
    max_emoji_ratio: 0.1  # Maximum 10% emojis
    max_punctuation_ratio: 0.2  # Maximum 20% punctuation
    max_number_ratio: 0.3  # Maximum 30% numbers
    enforce_region_filter: false  # Default: can be overridden per channel
    
  # Regional filtering settings
  regional:
    strict_mode: false  # If true, only exact region matches
    flexible_mode: true  # If true, check aliases and variations
    log_filtered_reports: true  # Log region-filtered reports
    
  # Common exclude patterns for non-violation content
  exclude_patterns:
    - "طقس"
    - "أحوال جوية"
    - "اقتصاد"
    - "سياسة"
    - "رياضة"
    - "ترفيه"
    - "تكنولوجيا"
    - "تسويق"
    - "إعلان"
    - "عرض"
    - "خصم"
    - "تخفيض"
    - "سعر"
    - "بيع"
    - "شراء"
    - "تداول"
    - "بورصة"
    - "أسهم"
    - "عملة"
    - "دولار"
    - "يورو"
    - "ذهب"
    - "نفط"
    - "غاز"
    - "كهرباء"
    - "ماء"
    - "إنترنت"
    - "هاتف"
    - "كمبيوتر"
    - "برنامج"
    - "تطبيق"
    - "موقع"
    - "صفحة"
    - "فيديو"
    - "صورة"
    - "موسيقى"
    - "أغنية"
    - "فيلم"
    - "مسلسل"
    - "مباراة"
    - "فريق"
    - "لاعب"
    - "مدرب"
    - "ملعب"
    - "كأس"
    - "بطولة"
    - "دوري"
    - "نتيجة"
    - "فوز"
    - "خسارة"
    - "تعادل"
    
    # Official statements and announcements (to prevent processing as violations)
    - "وزارة الخارجية"
    - "الخارجية المصرية"
    - "الخارجية التركية"
    - "الخارجية الفرنسية"
    - "الرئاسة السورية"
    - "أدانت"
    - "أدان"
    - "تدين"
    - "تستنكر"
    - "استنكار"
    - "تنديد"
    - "شجب"
    - "شجبت"
    - "تحذر"
    - "تحذير"
    - "تطالب"
    - "يطالب"
    - "دعت"
    - "دعا"
    - "قالت"
    - "قال"
    - "أفادت"
    - "أفاد"
    - "صرحت"
    - "صرح"
    - "أكدت"
    - "أكد"
    - "أعلنت"
    - "أعلن"
    - "أعربت"
    - "أعرب"
    - "بيان"
    - "تصريح"
    - "مؤتمر"
    - "اجتماع"
    - "لقاء"
    - "زيارة"
    - "مفاوضات"
    - "اتفاقية"
    - "توقيع"
    - "وفقاً"
    - "وفقا"
    - "حسب"
    - "بحسب"
    - "وفق"
    - "نقل"
    - "نقلت"
    - "نقلاً"
    - "نقلا"