# Telegram Channels Configuration
# List of public Telegram channels to monitor for violations reports

channels:
  # Syrian Civil Defense (White Helmets)
  - name: "Naher Media"
    url: "https://t.me/nahermedia"
    description: "Naher Media"
    active: true
    priority: "medium"
    language: "ar"
    filtering:
      min_keyword_matches: 2
      require_context_keywords: true
      min_text_length: 30
      exclude_patterns: []

  - name: "Halab Today"
    url: "https://t.me/HalabTodayTV"
    description: "Halab Today"
    active: true
    priority: "low"
    language: "ar"
    filtering:
      min_keyword_matches: 1
      require_context_keywords: true
      min_text_length: 40

  - name: "صوت العاصمة"
    url: "https://t.me/damascusv011"
    description: "صوت العاصمة"
    active: true
    priority: "high"
    language: "ar"
    filtering:
      min_keyword_matches: 1
      require_context_keywords: true

  - name: "سوريا لحظة بلحظة"
    url: "https://t.me/Almohrar"
    description: "سوريا لحظة بلحظة"
    active: true
    priority: "medium"
    language: "ar"
    filtering:
      min_keyword_matches: 1
      require_context_keywords: true

  - name: "SNN"
    url: "https://t.me/ShaamNetwork"
    description: "SNN"
    active: true
    priority: "high"
    language: "ar"

  - name: "NEDAAPOST"
    url: "https://t.me/NEDAAPOST"
    description: "NEDAAPOST"
    active: true
    priority: "high"
    language: "ar"

  - name: "Reporters_sy"
    url: "https://t.me/Reporters_sy"
    description: "Reporters_sy"
    active: true
    priority: "high"
    language: "ar"

  - name: "sham_plus3"
    url: "https://t.me/sham_plus3"
    description: "sham_plus3"
    active: true
    priority: "high"
    language: "ar"

  - name: "مراسل الشرقية"
    url: "https://t.me/AbomosaabSharkea"
    description: "AbomosaabSharkea"
    active: true
    priority: "high"
    language: "ar"

  - name: "alkhabour"
    url: "https://t.me/alkhabour"
    description: "alkhabour"
    active: true
    priority: "high"
    language: "ar"

  - name: "D24net"
    url: "https://t.me/D24net"
    description: "D24net"
    active: true
    priority: "high"
    language: "ar"

# Scraping configuration
scraping:
  # How often to run the scraper (in minutes)
  interval: 5
  
  # How far back to look for messages (in minutes)
  lookback_window: 120
  
  # Maximum number of messages to process per channel per run
  max_messages_per_channel: 50
  
  # Timeout for HTTP requests (in seconds)
  request_timeout: 30
  
  # Retry configuration
  max_retries: 3
  retry_delay: 5000  # milliseconds
  
  # User agent for web scraping
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"