# Telegram Channels Configuration
# List of public Telegram channels to monitor for violations reports

channels:
  # Syrian Civil Defense (White Helmets)
  - name: "SyrianCivilDefence"
    url: "https://t.me/SyrianCivilDefence"
    description: "Syrian Civil Defense official channel"
    active: true
    priority: "high"
    language: "ar"
    
  # Syrian Observatory for Human Rights
  - name: "syriahr"
    url: "https://t.me/syriahr"
    description: "Syrian Observatory for Human Rights"
    active: true
    priority: "high"
    language: "ar"
    
  # Local News Networks
  - name: "Smart_Aleppo"
    url: "https://t.me/Smart_Aleppo"
    description: "Smart News Agency - Aleppo"
    active: true
    priority: "medium"
    language: "ar"
    
  - name: "DamascusNow_Sy"
    url: "https://t.me/DamascusNow_Sy"
    description: "Damascus Now News"
    active: true
    priority: "medium"
    language: "ar"
    
  - name: "HomsNow"
    url: "https://t.me/HomsNow"
    description: "Homs Now News"
    active: true
    priority: "medium"
    language: "ar"

  # Human Rights Organizations
  - name: "VDC_sy"
    url: "https://t.me/VDC_sy"
    description: "Violations Documentation Center"
    active: true
    priority: "high"
    language: "ar"
    
  - name: "snhr"
    url: "https://t.me/snhr"
    description: "Syrian Network for Human Rights"
    active: true
    priority: "high"
    language: "ar"

# Scraping configuration
scraping:
  # How often to run the scraper (in minutes)
  interval: 5
  
  # How far back to look for messages (in minutes)
  lookback_window: 5
  
  # Maximum number of messages to process per channel per run
  max_messages_per_channel: 50
  
  # Timeout for HTTP requests (in seconds)
  request_timeout: 30
  
  # Retry configuration
  max_retries: 3
  retry_delay: 5000  # milliseconds
  
  # User agent for web scraping
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"