# Arabic Keywords for Violation Types
# These keywords will be used to identify potential violations in scraped Telegram messages

keywords:
  AIRSTRIKE:
    - "غارة جوية"
    - "غارة"
    - "قصف"
    - "غارات جوية" 
    - "قصف جوي"
    - "طيران حربي"
    - "طائرات حربية"
    - "صواريخ جوية"
    - "ضربات جوية"
    - "هجوم جوي"
    - "قنابل"
    - "طيران"
    
  CHEMICAL_ATTACK:
    - "هجوم كيميائي"
    - "أسلحة كيميائية"
    - "غازات سامة"
    - "كلور"
    - "سارين"
    - "خانق"
    - "كيماوي"
    - "غاز"
    - "اختناق"
    - "تسمم"
    
  DETENTION:
    - "اعتقال"
    - "اعتقالات"
    - "محتجز"
    - "معتقل"
    - "معتقلين"
    - "سجن"
    - "احتجاز"
    - "مداهمة"
    - "اختفاء قسري"
    - "مفقود"
    
  DISPLACEMENT:
    - "نزوح"
    - "تهجير"
    - "نازحين"
    - "مهجرين"
    - "إخلاء"
    - "تهجير قسري"
    - "فرار"
    - "لاجئين"
    - "مخيمات"
    - "ترك المنازل"
    
  EXECUTION:
    - "إعدام"
    - "قتل"
    - "إعدامات"
    - "مقتل"
    - "ذبح"
    - "رمي من مكان عالي"
    - "إعدام ميداني"
    - "قتل على الهوية"
    - "جريمة قتل"
    - "موت"
    
  SHELLING:
    - "قصف"
    - "قذائف"
    - "هاون"
    - "مدفعية"
    - "راجمات"
    - "هجوم صاروخي"
    - "قذيفة"
    - "انفجار"
    - "قصف مدفعي"
    - "صواريخ أرض"
    
  SIEGE:
    - "حصار"
    - "محاصرة"
    - "حصار غذائي"
    - "منع وصول المساعدات"
    - "تجويع"
    - "منع دخول الطعام"
    - "إغلاق الطرق"
    - "حصار طبي"
    - "منع الأدوية"
    - "عزل"
    
  TORTURE:
    - "تعذيب"
    - "تعذيب جسدي"
    - "تعذيب نفسي"
    - "ضرب"
    - "صعق كهربائي"
    - "حرق"
    - "كسر عظام"
    - "انتهاك جسدي"
    - "وحشية"
    - "إهانة"
    
  MURDER:
    - "قتل"
    - "جريمة قتل"
    - "قتل عمد"
    - "قتل بدم بارد"
    - "جريمة"
    - "قاتل"
    - "مقتل"
    - "قتل مدني"
    - "استهداف مدنيين"
    - "ضحية"
    
  SHOOTING:
    - "إطلاق نار"
    - "رصاص"
    - "رصاصة"
    - "بندقية"
    - "نيران"
    - "قنص"
    - "قناص"
    - "أعيرة نارية"
    - "إصابة برصاص"
    - "رشق بالرصاص"
    - "اصابة"
    - "إصابة"
    
  HOME_INVASION:
    - "اقتحام منازل"
    - "دخول بالقوة"
    - "اقتحام بيوت"
    - "تفتيش منازل"
    - "مداهمة منازل"
    - "دخول غير قانوني"
    - "انتهاك حرمة المنزل"
    - "اقتحام"
    - "دخول عنوة"
    - "كسر أبواب"
    
  EXPLOSION:
    - "انفجار"
    - "إنفجار"
    - "تفجير"
    - "انفجارات"
    - "قنبلة"
    - "لغم"
    - "عبوة ناسفة"
    - "تفجير سيارة"
    - "انفجار سيارة"
    - "تفجير انتحاري"
    - "نسف"
    
  AMBUSH:
    - "كمين"
    - "نصب كمين"
    - "هجوم مفاجئ"
    - "مباغتة"
    - "اعتراض"
    - "هجوم خاطف"
    - "استهداف"
    - "مهاجمة"
    - "اعتداء"
    - "ضربة سريعة"
    
  KIDNAPPING:
    - "اختطاف"
    - "خطف"
    - "اختطافات"
    - "مخطوف"
    - "مختطف"
    - "أخذ بالقوة"
    - "خطف أطفال"
    - "خطف نساء"
    - "اقتياد قسري"
    - "إخفاء"
    
  LANDMINE:
    - "لغم أرضي"
    - "ألغام"
    - "لغم"
    - "ألغام أرضية"
    - "عبوة ناسفة"
    - "متفجرات مخفية"
    - "لغم مضاد للأشخاص"
    - "فخ متفجر"
    - "انفجار لغم"
    - "حقل ألغام"
    
  OTHER:
    - "انتهاك"
    - "جريمة حرب"
    - "جريمة ضد الإنسانية"
    - "انتهاك حقوق الإنسان"
    - "عنف"
    - "اعتداء"
    - "إساءة معاملة"
    - "قمع"
    - "انتهاكات"
    - "مذبحة"
    - "وفاة"
    - "موت"
    - "موت غير طبيعي"

# General context keywords that indicate potential violations
context_keywords:
  - "ضحايا"
  - "جرحى"
  - "قتلى"
  - "شهداء"
  - "مدنيين"
  - "أطفال"
  - "نساء"
  - "عائلات"
  - "مستشفى"
  - "مدرسة"
  - "مسجد"
  - "كنيسة"
  - "سوق"
  - "منازل سكنية"
  - "مخيم"
  - "إسعاف"
  - "جثث"
  - "دم"
  - "جروح"
  - "إصابات"
  - "اصابة"
  - "إصابة"
  - "دورية"
  - "تتمركز"
  - "حريق"
  - "احتراق"
  - "تدمير"
  - "اطلاق نار"
  - "نار"
  - "اغتيال"
  - "اغتيالات"
  - "إطلاق"
  - "إطلاق نار"
  - "إطلاق ناري"
  - "إطلاق نارية"
  - "إطلاق نارية"
  - "إغتيال"

# Exclusion patterns for non-violation content
exclude_patterns:
  # Announcements and meetings
  - "بدء اجتماع"
  - "اجتماع"
  - "مبعوث"
  - "سفير"
  - "دبلوماسي"
  - "زيارة"
  - "لقاء"
  - "مفاوضات"
  - "اتفاقية"
  - "توقيع"
  - "إعلان"
  - "بيان"
  - "تصريح"
  - "مؤتمر"
  - "ندوة"
  - "ورشة عمل"
  - "يدين"
  - "ادانة"
  - "إدانة"
  
  # Administrative and government activities
  - "جولة تفقدية"
  - "جولة"
  - "تفقدية"
  - "تحسين الخدمات"
  - "تطوير الخدمات"  
  # Official statements and condemnations (to prevent processing as violations)
  - "وزارة الخارجية"
  - "الخارجية المصرية"
  - "الخارجية التركية"
  - "الخارجية الفرنسية"
  - "الخارجية الأمريكية"
  - "الخارجية الروسية"
  - "الرئاسة السورية"
  - "أدانت"
  - "أدان"
  - "تدين"
  - "تدان"
  - "تستنكر"
  - "يستنكر"
  - "استنكار"
  - "تنديد"
  - "تنديدا"
  - "تنديداً"
  - "شجب"
  - "شجبت"
  - "شجبا"
  - "شجباً"
  - "استنكرت"
  - "استنكر"
  - "تحذر"
  - "تحذير"
  - "تحذيرا"
  - "تحذيراً"
  - "تطالب"
  - "يطالب"
  - "دعت"
  - "دعا"
  - "دعوة"
  - "نداء"
  - "نادى"
  - "نادت"
  - "نقل"
  - "نقلت"
  - "نقلاً"
  - "نقلا"
  - "وفقاً"
  - "وفقا"
  - "حسب"
  - "بحسب"
  - "وفق"
  - "طبقاً"
  - "طبقا"
  - "قالت"
  - "قال"
  - "أفادت"
  - "أفاد"
  - "صرحت"
  - "صرح"
  - "أكدت"
  - "أكد"
  - "أوضحت"
  - "أوضح"
  - "بينت"
  - "بين"
  - "أشارت"
  - "أشار"
  - "ذكرت"
  - "ذكر"
  - "أعلنت"
  - "أعلن"
  - "أعربت"
  - "أعرب"
  - "عبرت"
  - "عبر"
  - "أبدت"
  - "أبدى"
  - "according to"
  - "condemned"
  - "condemns"
  - "ministry"
  - "foreign ministry"
  - "statement"
  - "denounced"
  - "denounces"
  - "criticized"
  - "criticizes"
  - "warned"
  - "warns"
  - "called for"
  - "calls for"
  - "expressed"
  - "expresses"
  - "stated"
  - "states"
  - "declared"
  - "declares"
  
  # Economic and business
  - "اقتصاد"
  - "تجارة"
  - "استثمار"
  - "سوق"
  - "أسعار"
  - "عملة"
  - "بنك"
  - "شركة"
  - "مشروع"
  - "عقد"
  - "صفقة"
  
  # Infrastructure and development
  - "بنية تحتية"
  - "طريق"
  - "جسر"
  - "مطار"
  - "ميناء"
  - "كهرباء"
  - "ماء"
  - "غاز"
  - "إنترنت"
  - "اتصالات"
  - "بناء"
  - "تشييد"
  - "تطوير"
  
  # Sports and entertainment
  - "رياضة"
  - "كرة القدم"
  - "مباراة"
  - "فريق"
  - "لاعب"
  - "مدرب"
  - "ملعب"
  - "ترفيه"
  - "فن"
  - "موسيقى"
  - "سينما"
  - "مسرح"
  
  # Education and culture
  - "تعليم"
  - "جامعة"
  - "مدرسة"
  - "طالب"
  - "أستاذ"
  - "ثقافة"
  - "كتاب"
  - "مكتبة"
  - "متحف"
  - "معرض"
  
  # Health and medical (non-violation related)
  - "مستشفى"
  - "طبيب"
  - "علاج"
  - "دواء"
  - "مرض"
  - "وباء"
  - "لقاح"
  - "صحة"
  - "طبي"
  
  # Administrative and policy
  - "قانون"
  - "تشريع"
  - "مرسوم"
  - "قرار"
  - "تعميم"
  - "إدارة"
  - "موظف"
  - "وظيفة"
  - "راتب"
  - "تقاعد"
  
  # Technology and media
  - "تكنولوجيا"
  - "كمبيوتر"
  - "هاتف"
  - "إنترنت"
  - "برنامج"
  - "تطبيق"
  - "موقع"
  - "صفحة"
  - "فيديو"
  - "صورة"
  - "إعلام"
  - "صحافة"
# Location keywords for Syrian context
location_keywords:
  - "سوريا"
  - "دمشق"
  - "حلب"
  - "حمص"
  - "حماة"
  - "درعا"
  - "دير الزور"
  - "السويداء"
  - "القنيطرة"
  - "طرطوس"
  - "اللاذقية"
  - "الرقة"
  - "إدلب"
  - "الحسكة"
  - "ريف دمشق"